#!/usr/bin/env bash
COMMIT_MSG_FILE=$1

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

IFS='/'
if read -r _ DEFAULT_BRANCH <<< "$(git rev-parse --verify -q --abbrev-ref origin/HEAD)" && [ "$DEFAULT_BRANCH" = "$CURRENT_BRANCH" ]; then
    MESSAGE="; YOU'RE ON THE DEFAULT BRANCH.\n"

else
    extract_branch_prefix() {
        if [[ $1 == *"/"* ]]; then
            cut -d '/' -f 1 <<< "$1"
        else
            cut -d '-' -f 1-2 <<< "$1"
        fi
    }

    TASK_TYPE="$(extract_branch_prefix "$CURRENT_BRANCH")"
    MESSAGE="${TASK_TYPE}:"
fi

if [ -z "$(head -n 1 "$1")" ]; then
    sed -i "1s/^/${MESSAGE}/" "${COMMIT_MSG_FILE}";
fi

echo Preparing message for \"$CURRENT_BRANCH\". Prepared prefix: \"$MESSAGE\" >> /tmp/prepare-commit-msg.log
