theme = "nord-dark"
icons = "awesome5"

[[block]]
block = "focused_window"

[[block]]
block = "keyboard_layout"

[[block]]
block = "networkmanager"
primary_only = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {used}/{total}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} ({mem_used_percents})"
format_swap = "{swap_used_percents}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
hide_when_empty = true

[[block]]
block = "sound"
on_click = "pulsemixer --toggle-mute"
show_volume_when_muted = true

[[block]]
block = "xrandr"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %_H:%M"

[[block]]
block = "battery"
format = "{percentage}"

[[block]]
block = "notmuch"
query = "tag:unread +is:inbox -is:draft -is:sent"
maildir = "/home/thomas/mail"
threshold_info = 1
threshold_good = 10
threshold_warning = 100
