#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN || -z "${TMPDIR}" ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Path to your oh-my-zsh installation.
case $OSTYPE in
darwin*)
export ZSH=/Users/Thomas/.oh-my-zsh
export PATH="/Users/Thomas/.local/bin:/Users/Thomas/bin:$HOME/.cargo/bin:/opt/local/bin:/opt/local/sbin:/Users/Thomas/anaconda3/bin:$PATH:/usr/local/bin:./node_modules/.bin:/usr/local/lib/node_modules/flow-bin:$HOME/.rvm/bin"
export P4PORT="perforce-osl.funcom.com:1666"
export P4USER="thomasha"
export P4CLIENT="thomasha_home"
export P4EDITOR="$VISUAL"
export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
;;
linux*)
export ZSH=/home/thomas//.oh-my-zsh
export TERM="xterm-256color"
;; esac
